### ISSUE TITLE
Code clarity: Permutation for minimum loss

### ISSUE THREAD

**Issue by LukasDrude** [snsun/separation#5]
Hello,

your code is not quite clear, regarding Eq. (13) of the referenced paper. I can just find https://github.com/snsun/separation/blob/master/model/spknet.py#L149 in your code, but that does not use either `min()` nor `argmin()`.

Cheers.

**Comment by snsun** [comment]
Sorry for that.  Ignore the model/spknet.py. This is just a try to do speaker classification to help the separation. If you are care about PIT, you just need to focus on model/blstm.py L146-L155.

**Comment by LukasDrude** [comment]
Yes, I found it here: https://github.com/snsun/separation/blob/master/model/blstm.py#L154

Thank you for your response.
